### ISSUE TITLE
IncrementalClean deletes transitively-acquired content in Visual Studio

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#1054]
[This is based on feedback from `connect.microsoft.com`.]

If you have:
- A project that copies some files to the output directory (call it `ClassLibraryIndirect`)
- A project that depends on `ClassLibraryIndirect` (call it `ClassLibraryDirect`)
- A project that depends on `ClassLibraryDirect` (call it `IncrementalClean`)

And you build using Visual Studio, some very surprising behavior can occur.

Demo projects: https://github.com/rainersigwald/IncrementalCleanDemo

On the first (full) build of the main project, the output file is present in ClassLibraryIndirect's bin directory, **and** in IncrementalClean's--as expected. Content files should be transitively passed along. [Selected state](https://github.com/rainersigwald/IncrementalCleanDemo/commit/517e4e8e1a3acc16ec288ca320bf0d34ed039c3e).

If you make a change to the main project (to get VS's fast-up-to-date check to cause an actual build) and build just it again, the content file gets deleted from the main project's bin directory. [changes](https://github.com/rainersigwald/IncrementalCleanDemo/commit/e415ad7a74be41e78d910e424c941f5a9acded28)

Looking through a diag-level log of the second build, the problem is that the [`IncrementalClean`](https://github.com/Microsoft/msbuild/blob/e7019886b3fd520b547a7353d78d106d72a4b828/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L4463-L4520) target [deletes the file](https://github.com/rainersigwald/IncrementalCleanDemo/blob/e415ad7a74be41e78d910e424c941f5a9acded28/build-main-project-in-vs-again.log#L5188), because it incorrectly [thinks it's no longer an output](https://github.com/rainersigwald/IncrementalCleanDemo/commit/e415ad7a74be41e78d910e424c941f5a9acded28#diff-414497d138b9a3671970cce983188d2cL1).

This [does **not** happen](https://github.com/rainersigwald/IncrementalCleanDemo/commit/7a9717e0aa9fb07ce1769781cf98d866bd5ae290) when building from the command line using no special properties.

But it [**does** happen](https://github.com/rainersigwald/IncrementalCleanDemo/commit/5a3eba2d01f91a16a4463209fed638def3b6d566) when building from the command line setting the property `BuildProjectReferences=false`, which simulates Visual Studio's mechanism of building individual projects.

Whether or not a project is built in isolation should not affect the outputs it produces.

**Comment by rainersigwald** [comment]
The proximate cause of this is that the transitive [`GetCopyToOutputDirectoryItems`]() target [doesn't include the indirect content file](https://github.com/rainersigwald/IncrementalCleanDemo/blob/e415ad7a74be41e78d910e424c941f5a9acded28/build-main-project-in-vs-again.log#L4266-L4269) in the latter build, while it [does](https://github.com/rainersigwald/IncrementalCleanDemo/blob/e415ad7a74be41e78d910e424c941f5a9acded28/build-main-project-in-vs.log#L9318-L9325] in the initial, successful build as well as the [successful full command-line build](https://github.com/rainersigwald/IncrementalCleanDemo/blob/7a9717e0aa9fb07ce1769781cf98d866bd5ae290/msbuild-main-project-build-again.log#L9860-L9867).

There's a [very confusing comment](https://github.com/Microsoft/msbuild/blob/e7019886b3fd520b547a7353d78d106d72a4b828/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L4091-L4100) for `GetCopyToOutputDirectoryItems` that indicates that it isn't transitive--but clearly sometimes it is.

**Comment by kzu** [comment]
We're hitting this too, trying to improve the way we perform the Pdb>Mdb in-place, and not getting them copied transitively :(

**Comment by abbottbd** [comment]
+1 this has been a thorn in our side at work for ages!

**Comment by aswinraaj** [comment]
We are getting the same problem when using sonarqube for performing static code analysis which creates temporary files . Incremental clean deletes it before the entire solution is even completed building

**Comment by jcouv** [comment]
+1 I'm hitting this daily in my inner development loop.

**Comment by anjdreas** [comment]
We worked around this by moving all content files from each individual library, where we feel they naturally belong, to dumping all of them in our main app project. It's not pretty, but it works. We have spent way too much time investigating this and very frustrated to see the age of this problem and no update on fixing this.

**Comment by KirillOsenkov** [comment]
We've been hitting this as well and the easy workaround we found is to add:
```
<Target Name="IncrementalClean" />
```
to a .targets file that's included in all projects. Disabling incremental clean is mostly harmless since we regularly do `git clean -xdff` anyway. A decent workaround.

**Comment by rainersigwald** [comment]
Another workaround is to flatten your dependency tree: ensure that there are direct ProjectReferences instead of relying on transitive copying behavior.

**Comment by gulbanana** [comment]
I can confirm that I was extremely surprised by this behaviour. The symptom is a failure to *pack*, since the PDB file isn't present as an input to nuget, which the pack targets require even if you aren't building a symbol package..

**Comment by gulbanana** [comment]
As described in this StackOverflow question, over-cleaning affects more than just transitively-present contentfiles. https://stackoverflow.com/questions/44175371/pdb-file-is-being-removed-by-target-incrementalclean

**Comment by herrgruebner** [comment]
2018 and still going on. Was a fun one to track down.

**Comment by herrgruebner** [comment]
In our case we were using msbuild as part of a powershell script with the 'clean' parameter. We put a bit at the start of the script to blow away the output directory and got rid of the clean, which isn't great, but it works.

**Comment by akoessler** [comment]
Is there any plan to fix this issue in the near future?

**Comment by cclauson** [comment]
Just encountered this, is bugging some people at my organization, would love it if it were fixed! :)

**Comment by cclauson** [comment]
Hello,

I spent some time debugging this in structured log viewer, and eventually reached the same conclusion that is described in this comment mentioned by @rainersigwald :
https://github.com/Microsoft/msbuild/blob/e7019886b3fd520b547a7353d78d106d72a4b828/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L4091-L4100
(should have read this at the beginning...)

Succinctly, the target _SplitProjectReferencesByFileExistence consumes @(ProjectReferenceWithConfiguration), which is computed in the target AssignProjectConfiguration.  The bug occurs when _SplitProjectReferencesByFileExistence is run without first running AssignProjectConfiguration.

As a workaround, I'm currently putting the following code in a file which is imported by all my projects:
    <Target Name="ForceAssignProjectConfigurationBeforeSplitProjectReferencesByFileExistence_KLUDGE"
          BeforeTargets="_SplitProjectReferencesByFileExistence"
          DependsOnTargets="AssignProjectConfiguration" />

Am not noticing any problems or performance degradation.  Unless I'm missing something, maybe the fix is to add DependsOnTargets="AssignProjectConfiguration" to the _SplitProjectReferencesByFileExistence target in Microsoft.Common.CurrentVersion.targets?

Also, I tried @rainersigwald repro project here:
https://github.com/rainersigwald/IncrementalCleanDemo
Have confirmed that this approach fixes it.

**Comment by Drachenkaetzchen** [comment]
I'm having a similar issue. Upon a clean build, everything works fine. Once I rebuild, I see that all references are visible in explorer for a second, then are deleted. In fact, setting MSBuild output to verbose showed me that IncrementalClean was executed, leading me to this issue.

I did not have any <Content/> files in my referred projects, so this was extremely brutal to track down.

In my case, the culprit was FodyWeavers. I used to run `Fody 3.2.9`. After upgrading to `Fody 3.2.17`, the problem started. 

After lots of investigation, I found out that the issue started with `Fody 3.2.12` where as with `Fody 3.2.11` it works fine. Symptom is that with `Fody 3.2.12`, the affected referred project always gets rebuilt, causing the issue. That's how I actually found out about Fody in the first place; I went through all projects in my solution, clicking "rebuild" and seeing if VS thinks they're up-to-date or are rebuilt. 

In fact, it seems that this only happens if you're using `Packages.config`. `Fody 3.2.14` fixes this.

I understand that this comment is not strictly related to the original issue, but as it was extremely hard to track down and during my research I also stumbled over this issue like many others having similar effects, I thought it's valid to publish my findings.

**Comment by pasha-top** [comment]
> The proximate cause of this is that the transitive `GetCopyToOutputDirectoryItems` target [doesn't include the indirect content file](https://github.com/rainersigwald/IncrementalCleanDemo/blob/e415ad7a74be41e78d910e424c941f5a9acded28/build-main-project-in-vs-again.log#L4266-L4269) in the latter build, while it [does](https://github.com/rainersigwald/IncrementalCleanDemo/blob/e415ad7a74be41e78d910e424c941f5a9acded28/build-main-project-in-vs.log#L9318-L9325) in the initial, successful build as well as the [successful full command-line build](https://github.com/rainersigwald/IncrementalCleanDemo/blob/7a9717e0aa9fb07ce1769781cf98d866bd5ae290/msbuild-main-project-build-again.log#L9860-L9867).
> 
> There's a [very confusing comment](https://github.com/Microsoft/msbuild/blob/e7019886b3fd520b547a7353d78d106d72a4b828/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L4091-L4100) for `GetCopyToOutputDirectoryItems` that indicates that it isn't transitive--but clearly sometimes it is.

Thanks, it is worked!)
Unexpected behavior msbuild break my brain)
For transit copying files is necessary, than in transit project have been at least one file with mark "Copy if never/Copy always"

**Comment by superware** [comment]
Any plans to fix this **critical** issue anytime soon? @rainersigwald?

**Comment by jeremysimmons** [comment]
Thanks @cclauson 

I used [`Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017) to apply this to all my csproj files at once, without having to edit them. 

```
    <Project>
      <Target 
        Name="ForceAssignProjectConfigurationBeforeSplitProjectReferencesByFileExistence_KLUDGE" 
        BeforeTargets="_SplitProjectReferencesByFileExistence" 
        DependsOnTargets="AssignProjectConfiguration" />
    </Project>
```

**Comment by InKahootz** [comment]
Even after trying to apply the target in my top most Directory.Build.props it will still clean out my transitively acquired files from time to time.

**Comment by pratthinds** [comment]
I am experiencing essentially the same issue as InKahootz. 

The issue is happening when an incremental build occurs on a project that does not contain the Nuget dependencies directly. The unmanaged DLLs for some reason are incorrectly removed by the IncrementalClean step -- they should be left alone.

**Comment by livarcocc** [comment]
Assigning to @rainersigwald and 16.5 P1 because it seems it is being fixed by #4865. If that's not the case, we can move this back to backlog and un-assign.

**Comment by Chiel92** [comment]
How and where do I use this fix? I'm still suffering from this problem and I can't find information on the newly introduced `MSBuildCopyContentTransitively `.

**Comment by Chiel92** [comment]
I'm still experiencing this issue in Visual Studio Version 16.5.4. This issue is closed implying that it should be fixed. @rainersigwald Do I require to make changes to my project structure in order to have this fixed? Or should it work out of the box (which it doesn't, so that would imply I should make a new issue?))

**Comment by kobbe** [comment]
I can also confirm that it is not fixed

**Comment by kobbe** [comment]
How do you set `MSBuildCopyContentTransitively` to `true` in `Directory.Build.props`? I can't any example.

I used the solution from https://github.com/dotnet/msbuild/issues/4677 which worked:

```
<Target Name="EnsureContentIsTransitive"
        DependsOnTargets="AssignProjectConfiguration;_SplitProjectReferencesByFileExistence"
        Condition=" '$(MSBuildCopyContentTransitively)' == 'true' " />
```

**Comment by kzu** [comment]
@kobbe I guess it would simply be:

```xml
<Project>
  <PropertyGroup>
    <MSBuildCopyContentTransitively>true</MSBuildCopyContentTransitively>
  </PropertyGroup>
</Project>
```

**Comment by jakubsuchybio** [comment]
> Another workaround is to flatten your dependency tree: ensure that there are direct ProjectReferences instead of relying on transitive copying behavior.

To flatten the project references you can use 
```
    <PropertyGroup>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>
```
from https://github.com/dotnet/sdk/issues/11803

**Comment by rainersigwald** [comment]
@jakubsuchybio if you're _not_ setting that, you already have the dependency tree flattened by default, so you shouldn't hit this issue.

**Comment by jakubsuchybio** [comment]
Well, I didn't have it set and it was not flattened, because after setting it a whole lot of projects had missing references. I'm currently in process of fixing rebuilding of the solution of 185+ projects. IncrementalClean doesn't work properly on our resources (images, files, unmanaged dlls, etc). When doing Clean All and then Build All, it works fine, but when trying Rebuild it always fails on some file could not been copied. I tried to discuss it with @KirillOsenkov, but so far with no luck. Maybe it is not IncrementalClean problem, because even when i override it with `<Target Name="IncrementalClean" />` it still fails randomly.

**Comment by KirillOsenkov** [comment]
Feel free to send me a binlog privately and I can take a look

**Comment by KirillOsenkov** [comment]
Related but not the same: https://github.com/dotnet/msbuild/issues/9709
