### ISSUE TITLE
Msbuild sourcelinks broken

### ISSUE THREAD

**Issue by mmitche** [dotnet/msbuild#6375]
```
File lib/net472/Microsoft.Build.pdb has broken links:
		Failed to retrieve https://devdiv.visualstudio.com/DevDiv/_apis/git/repositories/DotNet-msbuild-Trusted/items?api-version=1.0&versionType=commit&version=117a9cbe207cf136e5d99fc6645a5ebc06b478c0&path=/src/Shared/FileSystem/CachingFileSystemWrapper.cs
		Failed to retrieve https://devdiv.visualstudio.com/DevDiv/_apis/git/repositories/DotNet-msbuild-Trusted/items?api-version=1.0&versionType=commit&version=117a9cbe207cf136e5d99fc6645a5ebc06b478c0&path=/src/Shared/FileSystem/FileSystems.cs
...
```

Looks like after the switch of repo uris to the azdo uri, that sourcelink is broken. I think it's likely that the automated translation to github uri just isn't quite working for that form.

/cc @tmat @dotnet/dnceng @alexperovich

**Comment by MattGal** [comment]
taking a look...

**Comment by MattGal** [comment]
@mmitche where does that log come from?  I loaded both https://devdiv.visualstudio.com/DevDiv/_apis/git/repositories/DotNet-msbuild-Trusted/items?api-version=1.0&versionType=commit&version=117a9cbe207cf136e5d99fc6645a5ebc06b478c0&path=/src/Shared/FileSystem/CachingFileSystemWrapper.cs and https://devdiv.visualstudio.com/DevDiv/_apis/git/repositories/DotNet-msbuild-Trusted/items?api-version=1.0&versionType=commit&version=117a9cbe207cf136e5d99fc6645a5ebc06b478c0&path=/src/Shared/FileSystem/FileSystems.cs in a browser and they gave me exactly what I'd expect.

**Comment by MattGal** [comment]
Oh it's probably https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L56

**Comment by marcpopMSFT** [comment]
@mmitche @MattGal is this fix now and can be closed?

**Comment by MattGal** [comment]
> @mmitche @MattGal is this fix now and can be closed?

Yes, I think this was fixed via the work done for https://github.com/dotnet/arcade/issues/7255

**Comment by mmitche** [comment]
It looks like the links are still broken: https://dev.azure.com/dnceng/internal/_build/results?buildId=1330515&view=logs&j=28bdc2c7-156f-51fb-6444-d4b8da3693ac&t=db80a514-da0d-59b3-7d70-a8c1f2a0491a&l=722

It should have the public github repo URI.

**Comment by adiaaida** [comment]
I think this might be because we didn't update the SourceRoot ScmRepositoryUrl like we did the one not associated with SourceRoot:

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L76

vs

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L70-L71

**Comment by adiaaida** [comment]
new PR: https://github.com/dotnet/arcade/pull/7844

**Comment by marcpopMSFT** [comment]
@dotnet/kitten should adopt a new arcade build that includes 7844 and we should close this.

**Comment by rainersigwald** [comment]
@adiaaida We are now up to date on Arcade 6.0--can you tell us how to validate and close this?

**Comment by adiaaida** [comment]
We might be able to run a validation pipeline run for the build (it requires special parameters, so I want to make sure we get it right). Do you have the official build where this change went in/published.

**Comment by adiaaida** [comment]
I started https://dev.azure.com/dnceng/internal/_build/results?buildId=1366299&view=results which hopefully is using the correct build. Will let you know what the outcome of that is

**Comment by adiaaida** [comment]
Looks like the sourcelink job completed successfully: https://dev.azure.com/dnceng/internal/_build/results?buildId=1366299&view=logs&j=28bdc2c7-156f-51fb-6444-d4b8da3693ac&t=db80a514-da0d-59b3-7d70-a8c1f2a0491a.

I'm going to also confirm that this fails on a build prior to this change, just to prove to myself that this isn't a false positive.

**Comment by adiaaida** [comment]
I have confirmed that the latest build of DotNet-msbuild-Trusted as github sourcelinks. I am closing this issue.

**Comment by rainersigwald** [comment]
Thanks, @adiaaida!
