### ISSUE TITLE
[NETSDKE2E][Loc]With NET9 SDK installed in loc OS(Chinese), Unit of time in message is missing when creating project in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#9601]
1. Install 9.0.100-alpha.1.24053.14 in Loc OS(e.g Chinese OS)
2. Run "dotnet new console" in CLI.
3. Check if the messages are localized well.

Expected Result:
the messages are localized well.

Actual Result:
Unit of time in message is missing.

Chinese(Repro)
![image](https://github.com/dotnet/sdk/assets/65637796/8ad754a4-94b3-41bc-bf19-cf20b9b25636)

EN:
![image](https://github.com/dotnet/sdk/assets/65637796/fa9ceef9-3f90-4b62-8479-2bca1695fad5)

German(not repro)
![image](https://github.com/dotnet/sdk/assets/65637796/4ff444f0-5b73-4b5e-9136-8f0151bd000c)

C:\Users\v-danche>dotnet --info
.NET SDK:
 Version:           9.0.100-alpha.1.24053.14
 Commit:            48543d2076
 Workload version:  9.0.100-manifests.b3326be0

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.24053.14\

已安装 .NET 工作负载:
没有要显示的已安装工作负载。

Host:
  Version:      9.0.0-alpha.1.24053.1
  Architecture: x64
  Commit:       cc26196708

.NET SDKs installed:
  9.0.100-alpha.1.24053.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.23620.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24053.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.24053.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
This appears to be the new terminal logger output so routing to msbuild and marking it for TL tracking.

**Comment by vdanche** [comment]
we checked on today's build 9.0.100-preview.1.24101.4 SDK,
the time unit is added for log output after running "dotnet new console" 
![image](https://github.com/dotnet/msbuild/assets/65637796/c1c93f95-b4a3-4e8e-848c-db84e4dc444f)

But the time unit is still missing after running "dotnet build"
![image](https://github.com/dotnet/msbuild/assets/65637796/003b2132-b7ad-4c6a-ab8e-896d141250f0)

**Comment by AR-May** [comment]
It should be already fixed with the fix of this issue: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/935605

**Comment by vdanche** [comment]
@AR-May It still happen when building project on Chinese OS on 9.0.100-preview.3.24165.20(runtime-9.0.0-preview.3.24162.31), Do we need to file a new bug for it?
![image](https://github.com/dotnet/msbuild/assets/65637796/0be19ecd-f1bc-4039-97ca-2e310b2ea563)

EN:
![image](https://github.com/dotnet/msbuild/assets/65637796/63946d36-69a8-4c6c-9d18-79d01bb89606)

**Comment by AR-May** [comment]
It seems like not everything was indeed fixed by the issue that I mentioned. I will reopen this issue, no need to create new one.

**Comment by AR-May** [comment]
Team triage: @JaynieBai Could you please fill a localization bug like the one I mentioned above.

**Comment by JaynieBai** [comment]
> Team triage: @JaynieBai Could you please fill a localization bug like the one I mentioned above.

Log bug https://ceapex.visualstudio.com/CEINTL/_workitems/edit/956251

**Comment by JaynieBai** [comment]
Translated in localization PR https://github.com/dotnet/msbuild/pull/10003

**Comment by vdanche** [comment]
@AR-May we checked on 9.0.100-preview.4.24224.4
Now, the unit of time can be displayed well after running "dotnet build"
![image](https://github.com/dotnet/msbuild/assets/65637796/f61865d1-656a-41eb-b59f-259b9a50447b)
But when we run "dotnet build -f net9.0", unit of time is still missing
![image](https://github.com/dotnet/msbuild/assets/65637796/b580101a-3597-4782-8349-4d7287fc7341)

EN
![image](https://github.com/dotnet/msbuild/assets/65637796/ed178574-241a-4d18-968d-f368a5d090c9)

**Comment by AR-May** [comment]
When you set up the framework, it is a separate string indeed. And it is not translated well it seems. 
@JaynieBai could you please open a loc bug for it too?

**Comment by v-shuli1** [comment]
not repro on ![image](https://github.com/user-attachments/assets/d35d5301-b028-4d63-9ea1-8988f5c677a9)

**Comment by v-shuli1** [comment]
Not repro on 9.0.100-rc.2.24452.3 (runtime-9.0.0-rc.2.24429.19)
![image](https://github.com/user-attachments/assets/33908b91-473f-4d90-8c60-d78dd1d3cdfc)
