### ISSUE TITLE
[BUG] Multiple instances of .NET host, hogging more than 95% memory and CPU

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#9922]
From vscode-dotnettools created by [dibarbet](https://github.com/dibarbet): microsoft/vscode-dotnettools#518  

### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/6344

## Issue Description ##
Multiple instances of .NET process. We have 42 csproj in our microservices-based solution. And every time I build the solution, the multiple .NET process gets spawned hogging up 95% of the CPU. And after building the instances do not get disposed of or close, they just sit there on RAM without any reason hogging up RAM as well. 
I would suggest please find a better way to reuse the instances of the .NET host to build the solution and to keep some data between the builds so that we can stop building unchanged projects just like Visual Studio. Because spinning up the process every time does not look viable solution in the long run. Below are the screenshots. If you see closes the CMD instances are still there, I guess we can shut them once the build is complete just like .NET process. 

<details>

When building.
![image](https://github.com/dotnet/vscode-csharp/assets/17148381/a5df1393-e294-422f-bc83-9f0d04ecc48e)
After the build is done. 
![image](https://github.com/dotnet/vscode-csharp/assets/17148381/d6efb792-790e-406f-8014-898387bd1073)

</details>

## Expected Behavior ##
.NET instances should be reused to build projects and should get closed once done. 

## Actual Behavior ##
Multiple instances are spawned and does not get disposed. 

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.82.0
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10-win32-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|darker-dark|XavierNaves|1.0.0|xaviernaves.darker-dark-1.0.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.13.0|usernamehw.errorlens-3.13.0|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|powershell|ms-vscode|2023.9.1|ms-vscode.powershell-2023.9.1|
|sonarlint-vscode|SonarSource|3.21.0|sonarsource.sonarlint-vscode-3.21.0-win32-x64|
|vim|vscodevim|1.26.0|vscodevim.vim-1.26.0|
|vscode-autohotkey2-lsp|thqby|2.1.5|thqby.vscode-autohotkey2-lsp-2.1.5|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

**Comment by arkalyanms** [comment]
@ladipro this is in relation to email convo to tweak process lifetimes for the MSBuild worker processes.

**Comment by dangducthinh** [comment]
Do we have any solution for this issue, I'm still suffering while using c# dev kit for large solution include a lot of projects. Visual Studio are working fine by the way. Hope we will find solution soon. Thank you all.

**Comment by dangducthinh** [comment]
look like this bug was fixed, tks team.
![image](https://github.com/user-attachments/assets/9ed1b663-b506-4e09-ba48-291748bccfac)

Version:
C# Dev Kit v1.8.14
C# v2.39.29

**Comment by alahane-techtel** [comment]
I can still see this issue happening. I use Viasul Studio 2022. In the screenshot, there is no visual studio  running, still I see so many ".Net Host" tasks. @AR-May , @JanKrivanek , may be we should re-open this issue?

![Image](https://github.com/user-attachments/assets/53ee79b3-f3aa-4fc0-abe3-1783024ec6d7)

**Comment by BoBoBaSs84** [comment]
@alahane-techtel can confirm this.

![Image](https://github.com/user-attachments/assets/1b4f1dec-5495-4247-bf8d-e970870279f4)

**Comment by alahane-techtel** [comment]
This is consistently happening. CPU and memory full again today. Cant do a thing. Even to click restart, I will have to wait few minutes for the button to come up :(

Noticed that this happened when I start debugging the .Net core WebAPI in C# .Net 8. I'm also using NSwag for openAPI generation and client code generation. Noticed that as soon as I added NSwag into the mix, this started happening.

![Image](https://github.com/user-attachments/assets/ef072dc5-6b5e-4aef-939d-e1e1291289e2)

**Comment by Gnog3** [comment]
Still happening on Visual Studio 2022

<img width="549" height="269" alt="Image" src="https://github.com/user-attachments/assets/0785307f-3228-4db6-b75d-52caa25defd9" />

**Comment by lofcz** [comment]
Can confirm this still happens. Interim here is a quick c++ utility which periodically kills .NET Host processes allocating excessive memory while also running too long: https://github.com/lofcz/dotnetmon

**Comment by ryancole** [comment]
It's 02-12-2026 and I am experiencing this issue. I'm running dotnet version 10.0.103 - the latest v10 at the moment of posting. I'm running the command `dotnet run` inside of an asp.net core web application's project folder. It's spawning many host processes and also fails to close them when I `CTRL+C` the program to close it.

**Comment by KoditkarVedant** [comment]
The issue still persists

**Comment by BDisp** [comment]
After closing VS Code, these processes usually terminate after a certain amount of time. If you really want to terminate them immediately and are sure they are not being used in any other app, you have to kill all `.NET Host` processes, but this is really annoying.

**Comment by JanProvaznik** [comment]
triage: 
this has a local mitigation `dotnet build-server shutdown`

we will discuss in the team the longer term strategy for the VSCode use case

**Comment by JanProvaznik** [comment]
continuation: there are tradeoffs: it is currently intended behavior that msbuild processes persist after vscode shutdown.
It's a reasonable request for C# devkit not to do that or expose a setting nicely so you can tune it for your case. MSbuild exposes API to shutdown. Also if you don't like this behavior you can set the nodes to timeout faster with environment variable `MSBUILDNODECONNECTIONTIMEOUT`
